/* Define custom server-side HTTP routes for lineman's development server
 *   These might be as simple as stubbing a little JSON to
 *   facilitate development of code that interacts with an HTTP service
 *   (presumably, mirroring one that will be reachable in a live environment).
 *
 * It's important to remember that any custom endpoints defined here
 *   will only be available in development, as lineman only builds
 *   static assets, it can't run server-side code.
 *
 * This file can be very useful for rapid prototyping or even organically
 *   defining a spec based on the needs of the client code that emerge.
 *
 */

module.exports = {
  drawRoutes: function(app) {
    app.post('/login', function(req, res) {
      res.json({ message: 'logging in!' });
    });

    app.post('/logout', function(req, res) {
      res.json({ message: 'logging out!'});
    });

    app.get('/vendors/data', function (req, res) {
      res.json([
  {
    "vendor": "A. Brown & Sons Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/a_brown_and_sons.png",
    "availability": "yessir",
    "website": "www.sales@brownsnursery.com",
    "description": "With over 1000 acres in production, A.Brown has been producing high quality trees, shrubs, and perennials since 1950.",
    "categories": ["Trees & Shrubs"],
    "location": "OH",
    "images": [
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_000.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_001.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_002.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_003.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_004.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_005.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_006.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_007.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_008.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_009.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_010.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_011.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_012.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_013.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_014.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_015.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_016.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_017.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_018.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_019.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/a_brown_and_sons/a_brown_and_sons_020.JPG"
      ],
  },
  {
    "vendor": "Balamore Farms",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/balamore_farms.png",
    "availability": "",
    "website": "http://balamore.com/",
    "description": "A third generation family run farm.",
    "categories": ["Perennials", "b/r"],
    "location": "Nova Scotia",
    "images": []
  },
  {
    "vendor": "Black Lake Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/black_lake_nursery.png",
    "availability": "",
    "website": "",
    "description": "For 32 years BLN has built a reputation for producing exceptional arborvitae, boxwood, and 3GL perennials. John Bulthouse does most of his own propagation, and can offer liners that are extremely well established.",
    "categories": ["Trees & Shrubs"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Blue Heron Farm",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/blue_heron_farm.png",
    "availability": "",
    "website": "www.bhfnursery.com/",
    "description": "Blue Heron Farm is a wholesale grower located in the fertile Willamette Valley of western Oregon. We currently grow over 850 varieties ranging from container trees and shrubs, bare root trees and balled and burlapped trees and conifers.",
    "categories": ["Container", "Trees & Shrubs"],
    "location": "OR",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_000.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_001.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_002.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_005.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_006.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_007.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_009.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_010.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_011.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_012.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_013.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_014.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_015.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_016.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_017.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_018.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_019.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_020.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_021.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_022.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_023.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_024.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_025.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_026.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_027.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_028.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_029.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_030.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_031.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_032.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_033.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_034.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_035.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_036.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_037.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_038.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_039.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/blue_heron_farms/blue_heron_farms_040.JPG"
    ],
  },
  {
    "vendor": "Casa Flora",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/casa_flora.png",
    "availability": "",
    "website": "",
    "description": "Casa Flora is a world-leading producer of fern liners, both hardy and tropical varieties.",
    "categories": ["Hardy Fern", "Perennial liners"],
    "location": "TX & FL",
    "images": []
  },
  {
    "vendor": "Creek Hill Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/creek_hill_nursery.png",
    "availability": "",
    "website": "www.creekhillnursery.com",
    "description": "Creek Hill Nursery is a growing liner production company nestled in the verdant valley of Lancaster County, PA. Creek Hill specialize in cell-pack starters of herbaceous perennials, ornamental grasses and deciduous woody plants.",
    "categories": ["Perennial liners"],
    "location": "PA",
    "images": []
  },
  {
    "vendor": "Donahue's Greenhouse",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/donahues_greenhouse.png",
    "availability": "",
    "website": "www.donahuesclematis.com",
    "description": "World class source of clematis, and hardy vines.",
    "categories": ["Clematis", "Vine liners"],
    "location": "MN",
    "images": []
  },
  {
    "vendor": "DGI Propagators",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/dgi_propagators.png",
    "availability": "",
    "website": "www.duwaynes.com",
    "description": " Formerly DuWaynes, DGI is arguably the best young plant grower in Michigan, DuWayne’s offers genetics from Syngenta, Ecke, Beekenkamp, GroLink, and Selecta. A one stop shop for annual liners, pre-finished geraniums, garden mum liners, and a rooting station for Beekenkamp’s full begonia line – and they are the best in the world!",
    "categories": ["Annual liners", "Prefinished"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Eckert's Greenhouse",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/eckerts_greenhouse.png",
    "availability": "",
    "website": "http://www.eckertsgreenhouse.com/H20LaborSaver.htm",
    "description": "Karl  invented the 'H20 Labor Saver' as well as the 'Weekender' hanging basket and stands. The full product line is available right here.",
    "categories": ["H2O Containers"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Emerald Coast Growers",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/emerald_coast_growers.png",
    "availability": "",
    "website": "www.ecgrowers.com",
    "description": "Founded in 1991, Emerald Coast Growers rapidly became a frontrunner in propagating ornamental grasses, and a respected liner producer of perennials and specialty annuals.",
    "categories": ["Ornamental liners", "Perennial liners"],
    "location": "FL, PA",
    "images": []
  },
  {
    "vendor": "Fairway Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/fairway_nursery.png",
    "availability": "",
    "website": "www.fairwaynursery.com",
    "description": "Fairway Nursery is a wholesale grower of ornamental nursery stock. Fairway specializes in providing newer, but tested and proven varieties of ornamental conifers, evergreens, and flowering plants.",
    "categories": ["Trees & Shrubs"],
    "location": "OR",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/fairway_nursery/fairway_nursery_018.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/fairway_nursery/fairway_nursery_022.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/fairway_nursery/fairway_nursery_023.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/fairway_nursery/fairway_nursery_031.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/fairway_nursery/fairway_nursery_036.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/fairway_nursery/fairway_nursery_039.JPG"
    ],
  },
  {
    "vendor": "Frank Henny & Sons Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/frank_henry_and_sons_nursery.png",
    "availability": "",
    "website": "",
    "description": "Frank Henry and Sons are wholesale growers for over 60 years. Their material is field-grown, landscape-size B&B plants. Primary products are deciduous azaleas, holly, laurels, Pieris, rhododendrons, and 10 varieties of boxwood up to 5 feet.",
    "categories": ["Shrubs"],
    "location": "OR",
    "images": []
  },
  {
    "vendor": "G&S Trees",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/g_and_s_trees.png",
    "availability": "",
    "website": "",
    "description": "Affordable trees grown in NC and TN - all B&B.",
    "categories": ["Trees & Shrubs"],
    "location": "NC, TN",
    "images": []
  },
  {
    "vendor": "Garden Solutions",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/garden_solutions.png",
    "availability": "",
    "website": "",
    "description": "Chris Hansen is breeding entire new lines of Hellebore, and Sedum. His introductions are revolutionizing these genus. You can purchase his liners here!",
    "categories": ["Perennial liners"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "GET Group",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/get_group.png",
    "availability": "",
    "website": "www.getgroupinc.com",
    "description": "High quality producer of 32 cell trays perennial liners.",
    "categories": ["Perennial liners"],
    "location": "IL",
    "images": []
  },
  {
    "vendor": "Great Garden Plants",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/great_garden_plants.png",
    "availability": "",
    "website": "www.greatgardenplants.com",
    "description": "Great Garden Plants specializes in shipping large, premium plants in Jumbo 1-Quart & 2 Quart pots. Great Garden Plants feature sun & shade-loving perennials, Knock Out Roses, Trees & Shrubs, colorful Heucheras, Ornamental Grasses.",
    "categories": ["Perennials"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "HMA Plants",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/hma_plants.png",
    "availability": "",
    "website": "",
    "description": "HMA Plants has been serving professional growers with innovative, quality ur/c's from some of the world’s top breeders since 1995. ",
    "categories": ["Unrooted Cuttings"],
    "location": "OH, Mexico",
    "images": []
  },
  {
    "vendor": "Hoffie Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/hoffie_nursery.png",
    "availability": "",
    "website": "www.hoffienursery.com",
    "description": "Hoffie Nursery is a wholesale grower of finished plant material, shipping throughout the midwest to Independent Garden Centers and Landscapers.",
    "categories": ["Perennials", "Finished"],
    "location": "IL",
    "images": []
  },
  {
    "vendor": "Hoffman Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/hoffman_nursery.png",
    "availability": "",
    "website": "www.hoffmannursery.com",
    "description": "For over 25 years, Hoffman Nursery has provided ornamental and native grasses to the wholesale horticultural trade. Hoffman specialize in grasses, sedges, and other grasslike plants.",
    "categories": ["Ornamental Grass liners"],
    "location": "NC",
    "images": []
  },
  {
    "vendor": "John den Haan & Son",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/john_den_haan_and_son.png",
    "availability": "",
    "website": "www.denhaannursery.com",
    "description": "In 1982 John den Haan began growing high quality bare root perennials near Coloma. John's son, Neal has taken over the busines, and is continuing the tradition of high quality, great service, and real value.",
    "categories": ["Perennials"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "K Drive Greenhouse",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/k_drive_greenhouse.png",
    "availability": "",
    "website": "www.kdrivegreenhouse.com",
    "description": "A specialty grower of annuals, perennials, and ground covers.  All grown as liners, and finished sizes.",
    "categories": ["Perennials"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Komrska Tree Farm",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/komrska_tree_farm.png",
    "availability": "",
    "website": "",
    "description": "When the MDA quarantined bringing Hemlocks into Michigan, Ben Komrska started planting them. Now for over 10 years he has been producing the highest quality fir, spruce, pine, birch, shade trees, amelanchier, and hemlock in northwest Michigan.",
    "categories": ["Trees & Shrubs"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Kraemer's Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/kraemers_nursery.png",
    "availability": "",
    "website": "www.kraemersnursery.com",
    "description": "Kraemer’s grow a wide diversity of woody and ornamental flowering shrubs, broadleaf evergreens, grasses, perennials, conifers, roses, vines, small fruits, Japanese maples and deciduous trees.",
    "categories": ["Trees & Shrubs"],
    "location": "OR",
    "images": []
  },
  {
    "vendor": "Loomis Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/loomis_nursery.png",
    "availability": "",
    "website": "www.loomisnursery.com",
    "description": "Linda Loomis grwos a wide selection of quality trees, shrubs and perennials from top growers, as well as one-of-a-kind specimens to make your garden truly exceptional.",
    "categories": ["Trees & Shrubs"],
    "location": "OR",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_000.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_001.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_002.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_003.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_004.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_005.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_006.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_007.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_008.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_009.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_010.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_011.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_012.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_013.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_014.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_015.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_016.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_017.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_018.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_019.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_020.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_021.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_022.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_023.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_024.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_025.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_026.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_027.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_028.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_029.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_030.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_031.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_032.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_033.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_034.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_035.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_036.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_037.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_038.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_039.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_040.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_041.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_042.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_043.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_044.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_045.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_046.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_047.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_048.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_049.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_050.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_051.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_052.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_053.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_054.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_055.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_056.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_057.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_058.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_059.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_060.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/loomis_nursery/loomis_nursery_061.JPG"
    ]
  },
  {
    "vendor": "Moose & Squirrel",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/moose_and_squirrel.png",
    "availability": "",
    "website": "www.moosesquirrelhort.com",
    "description": "A great source of finished annuals, perennials, azaleas, and small shrubs. Located SW of Detroit near Carleton.",
    "categories": ["Perennials", "Annuals"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "New Moon Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/new_moon_nursery.png",
    "availability": "",
    "website": "www.newmoonnursery.com",
    "description": "The premier source of native perennial liners, sedges, and grasses in North America.",
    "categories": ["Perennials", "Natives"],
    "location": "NJ",
    "images": []
  },
  {
    "vendor": "Peninsula Perennial Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/peninsula_perennial_nursery.png",
    "availability": "",
    "website": "www.pennurseries.com/",
    "description": "Complete source of perennials, liners to finished.",
    "categories": ["Perennials"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Northfield Farms",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/north_field_farms.png",
    "availability": "",
    "website": "www.northfieldfarms.com",
    "description": "NFF grows perennials like trees and shrubs. This means that all of their plants have undergone at least one growing season before they ship, and they are never “forced” in heated greenhouses. They are produced outdoors in the natural growing season. Northfield Farms is one of the top perennial nurseries in Michigan, with over 20 years of growing experience",
    "categories": ["Perennials", "Finished"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Provitro Biosciences",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/provitro_biosciences.png",
    "availability": "",
    "website": "www.provitrobio.com",
    "description": "The premier bamboo nursery in North America. Provitro offers bamboo liners, and finished plants up to 7 GL. Liners are grown in an on site tissue culture lab. Clumping, running, and ground cover bamboo are available. Boo Shoot also offers TC perennial liners, including Hakonachola.",
    "categories": ["TC Liners", "Bamboo"],
    "location": "WA",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_000.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_001.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_002.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_003.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_004.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_005.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_006.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_007.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_008.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_009.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_010.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_011.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_012.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_013.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_014.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_015.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_016.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_017.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/provitro_biosciences/provitro_biosciences_018.JPG"
    ]
  },
  {
    "vendor": "R & H Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/r_and_h_nursery.png",
    "availability": "",
    "website": "www.r-hnursery.com",
    "description": "Complete source of B&B Ornamentals",
    "categories": ["Trees & Shrubs"],
    "location": "OR",
    "images": []
  },
  {
    "vendor": "Rakers",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/rakers_nursery.png",
    "availability": "",
    "website": "www.raker.com",
    "description": " A one stop shop for liners, and young plants.",
    "categories": ["Perennials", "Annuals"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Reardon Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/reardon_nursery.png",
    "availability": "",
    "website": "www.reardonnursery.com",
    "description": "Reardon Nursery is a wholesale grower of container and field-grown broadleaf ornamentals (boxwood, Blue Holly, and Emerald Green Arbs) founded in 1978. The company is now in its third generation of family ownership and operation and is dedicated to providing customers with the best value possible.",
    "categories": ["Trees & Shrubs"],
    "location": "OR",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_000.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_001.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_002.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_003.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_004.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_005.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_006.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_007.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_008.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_009.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_010.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_011.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_012.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_013.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_014.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_015.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/reardon_nursery/reardon_nursery_016.JPG"
    ]
  },
  {
    "vendor": "Richard Gragg Nursry",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/richard_gragg_nursery.png",
    "availability": "",
    "website": "",
    "description": "Specimen grade arborvitae and boxwood. Located in western NC.",
    "categories": ["Trees & Shrubs"],
    "location": "NC",
    "images": [
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_000.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_001.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_002.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_003.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_004.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_005.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_006.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_007.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_008.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_009.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_010.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_011.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_012.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_013.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_014.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_015.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_016.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_017.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_018.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_019.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_020.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_021.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_022.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_023.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_024.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_025.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_026.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_027.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_028.JPG",
        "https://s3-us-west-2.amazonaws.com/greatgreensources/images/richard_gragg_nursery/richard_gragg_nursery_029.JPG"
      ]
  },
  {
    "vendor": "Robrick Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/robrick_nursery.png",
    "availability": "",
    "website": "www.robrick.com",
    "description": "Robrick Nursery Inc. produces young plants from cuttings for other growers, producing liners in either 105 or 72 cell trays.",
    "categories": ["Specimen Annual liners"],
    "location": "FL",
    "images": []
  },
  {
    "vendor": "Sawyer Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/sawyer_nursery.png",
    "availability": "",
    "website": "www.sawyernursery.com",
    "description": "A local source of perennial liners in Hudsonville, MI",
    "categories": ["Perennial liners"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Skagit Gardens",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/skagit_gardens.png",
    "availability": "",
    "website": "www.skagitgardens.com",
    "description": "Skagit sell a comprehensive selection of top-quality annuals and perennials. Located in the agricultural Skagit Valley, midway between Seattle, Washington and Vancouver, British Columbia where a mild maritime climate provides the ideal growing conditions for hardy perennials. If it is new, or just a great plant, Skagit has the liners.",
    "categories": ["Perennial liners"],
    "location": "WA",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_148.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_149.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_150.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_151.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_152.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_153.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_154.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_155.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_156.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_157.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_158.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_159.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_160.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_161.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_162.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_163.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_164.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_165.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_166.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/skagit_gardens/skagit_gardens_167.JPG"
    ]
  },
  {
    "vendor": "Stonehouse Nursery, LLC",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/stonehouse_nursery.png",
    "availability": "",
    "website": "www.stonehousenursery.com",
    "description": "The Steinhauser’s have a passion for growing the best perennial liners in the business. All of their perennials, grasses, and shrubs are grown in deep 32, or 50 cell trays in Kravo houses, insuring heavy, well toned plants.",
    "categories": ["Perennial liners"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Swift Greenhouses",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/swift_greenhouses.png",
    "availability": "",
    "website": "www.swiftgreenhouses.com",
    "description": "The original producer of perennial liners, their dormant 50 cell plug trays are still the standard bearer for the industry.",
    "categories": ["Perennial liners"],
    "location": "IA",
    "images": []
  },
  {
    "vendor": "Twin Springs Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/twin_springs_nursery.png",
    "availability": "",
    "website": "www.twinspringsnursery.com",
    "description": "Located in the heart of the fertile Willamette Valley of Western Oregon, Twin Springs Nursery is a 275 acre family owned and operated wholesale nursery. Twin Springs Nursery currently grows a broad variety of woody ornamentals with emphasis on Arborvitae, and Boxwood. ornamentals, offering both field grown and container plant. material.",
    "categories": ["Trees & Shrubs"],
    "location": "OR",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_122.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_123.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_124.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_125.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_126.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_127.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_128.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_129.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_130.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_131.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_132.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_133.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_134.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_135.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_136.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_137.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_138.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_139.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_140.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_141.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_142.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_143.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_144.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_145.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_146.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/twin_springs_nursery/twin_springs_nursery_147.JPG"
    ]
  },
  {
    "vendor": "Vandenberg Bulb Company",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/vandenberg_bulb_company.png",
    "availability": "",
    "website": "www.vandenbergbulb.com",
    "description": "A complete horticulture broker in Howell, MI",
    "categories": ["Broker"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Walters Gardens",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/walters_gardens.png",
    "availability": "",
    "website": "www.waltersgardens.com",
    "description": "The largest producer of perennials in North America.",
    "categories": ["Perennials"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Weesies Brothers Plant Farm",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/weesies_brothers_plant_farm.png",
    "availability": "",
    "website": "www.weesies.com",
    "description": "A third generation horticulturist, Mark Weesies takes great pride in growing great ground covers. We like to take orders by late Fall, to insure you get the plants you need. Mark grows them, we sell them at GGS!",
    "categories": ["Ground Covers", "Perennials"],
    "location": "MI",
    "images": []
  },
  {
    "vendor": "Wiggin's Nursery",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/wiggins_nursery.png",
    "availability": "",
    "website": "www.wigginsnursery.com",
    "description": "Wiggin's Nursery is a family owned business and specializes in propagating and growing many plants including cultivated conifer varieties, garden ornamental flowering trees and shrubs, broadleaf evergreens and a mix of specialty perennials.",
    "categories": ["Trees & Shrubs"],
    "location": "WA",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_014.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_015.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_016.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_017.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_018.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_019.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_020.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_021.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_022.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_023.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_024.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_025.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_026.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_027.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_028.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_029.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_030.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_031.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_032.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_033.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_034.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_035.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_036.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_037.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_038.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_039.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_040.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_041.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_042.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_043.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_044.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_045.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_046.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_047.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_048.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_049.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_050.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_051.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_052.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_053.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_054.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_055.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_056.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_057.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_058.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_059.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_060.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_061.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/wiggins_nursery/wiggins_nursery_062.JPG"
    ]
  },
  {
    "vendor": "Upton Valley Nursers",
    "image": "https://s3-us-west-2.amazonaws.com/greatgreensources/images/vendor_images/upton_valley_nursers.png",
    "availability": "",
    "website": "",
    "description": "Quality field production in western NC. Shade trees, dogwood, arborvitae, Pears, and hybrid rhododendron.",
    "categories": ["Trees & Shrubs"],
    "location": "NC",
    "images": [
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_063.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_064.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_065.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_066.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_067.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_068.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_069.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_070.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_071.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_072.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_073.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_074.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_075.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_076.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_077.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_078.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_079.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_080.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_081.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_082.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_083.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_084.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_085.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_086.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_087.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_088.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_089.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_090.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_091.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_092.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_093.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_094.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_095.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_096.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_097.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_098.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_099.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_100.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_101.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_102.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_103.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_104.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_105.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_106.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_107.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_108.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_109.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_110.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_111.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_112.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_113.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_114.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_115.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_116.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_117.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_118.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_119.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_120.JPG",
      "https://s3-us-west-2.amazonaws.com/greatgreensources/images/upton_valley_nursery/upton_valley_nursery_121.JPG"
    ]
  }
]);
  });
  }
};